### ISSUE TITLE
Problem with REQUEST_TIMEOUT init node.

### ISSUE THREAD

**Issue by CptanPanic** [aphysci/gravity#19]
I need some guidance. I am having the problem where I unable to start a node, and or unable to make a connection.  I will have 6+ nodes already started, and service directory seems to be ok, but if I try starting another one I just keep getting -3 returned, which is TIMEOUT I believe.  This is within a single machine, using tcp.  Using netstat, I can see the connection being made between the 2 processes, but they go away, and the retry happens again.  It seems to happen more often when I restart the node process.   And seems worse as the more nodes I have running.

Watching netstat here is what I see.
1. I see the tcp connection to the port 5555 to ServiceDirectory, but the node local port changes every 2 seconds, then after 6 seconds or so it  gives up. 
1. Restarting the node doesn't help, but restarting the ServiceDirectory does work.
1. Sometimes the node does succesfully connect, but there are no tcp connections made, and data product is not received correctly.
1. When I restart ServiceDirectory I get 2x number of connected tcp sockets. 

Any ideas?  I am able to reproduce, so let me know if you would like some more info.

**Comment by mbarger99** [comment]
@CptanPanic  - a few questions:

1. Is the timeout error being returned from init?  Or is this when you're trying to register something?
1. Are you using domains?
1. Are all the nodes using the same Gravity.ini?
1. What are the other nodes doing when you try to start the node that won't connect?
1. Is the CPU load high?

**Comment by CptanPanic** [comment]
Thanks for reply:
1. Timeout is from init, but have also seen it publishing data.
1. Yes I have a domain created, but not utilizing them, so if you think this would help, I can disable.
1. I am using ConfigServer, so have ServieDirectory and ConfigServer using Gravity.ini, and the rest getting served from config_file.ini
1. The other nodes seem to be happy, as they are still sending and receiving heartbeats, etc.
1. CPU load is very low.

**Comment by CptanPanic** [comment]
So it definetly seems to be related to the number of nodes connected to ServiceDirectory, and definitely get more problems as I get to 9-10 nodes.

**Comment by mbarger99** [comment]
That's strange - we've had a few projects with more GravityNode's using the same ServiceDirectory before.  My suspicion is that it's related to the ConfigServer - can you try running everything from a local config file?

**Comment by CptanPanic** [comment]
So I thought that could be it, so I disabled the ConfigServer, and moved everything into the Gravity.ini file, and still the same issue.  Monitoring netstat, things look pretty much the same.

**Comment by mbarger99** [comment]
Can you post your Gravity.ini and give us some more info about what each node is doing?  Are they just doing heartbeats?

**Comment by CptanPanic** [comment]
Attached is my config_file.ini .

But basically mostly just sending heartbeats.  The VehicleModel node is publishing data at 100Hz, and AutoPilot at 20Hz. 

[config_file.txt](https://github.com/aphysci/gravity/files/1830417/config_file.txt)

Thanks.

**Comment by mbarger99** [comment]
Thanks.  But you said that you tried disabling the ConfigServer and still saw the issue right?  So components would have just used what was in the Gravity.ini file in that case.  Can you post that?  Or is that identical to this?

**Comment by CptanPanic** [comment]
Yes that is the same thing except for NoConfigServer=true

**Comment by CptanPanic** [comment]
So I think I found the problem, it is the logger.  Here were my clues.

1. I stopped getting the connection timeout after adjusting the logging levels of both local and console to none, and I am able to connect all the nodes. At the time I didn't hit me what changed.
1. After problem above stopped happening, One of my nodes would work for 10-15 seconds and then would stop sending any heartbeats, etc.  I was able to attach to it with gdb and it was stuck calling fputc from gravity::Log(), I turned off LocalLogLevel, and it worked from then on.  
1. I went back and disabled 1. above, and verified that I got timeout, and then attached ServiceDirectory with gdb, and aha, I see the same deadlock after calling fputc.  See backtrace below:

So 2 things, yes I have no idea what would be causing the fputc to fail, but personally for critical stuff like this library I like to have the file writing in an new thread, so that if there are problems like this with writing to logging don't break operation.  What do you think?

```
#0  0x00007f2561e0785d in write () from /lib64/libc.so.6
#1  0x00007f2561d93fb3 in _IO_new_file_write () from /lib64/libc.so.6
#2  0x00007f2561d9541c in __GI__IO_do_write () from /lib64/libc.so.6
#3  0x00007f2561d957f3 in __GI__IO_file_overflow () from /lib64/libc.so.6
#4  0x00007f2561d91289 in fputc () from /lib64/libc.so.6
#5  0x00007f2563253d14 in FileLogger::Log (this=0x1522610, level=8,
    messagestr=0x7ffc149fc160 "[Lookup Request] ID: RegisteredPublishers, Domain: , MessageType: Data Product, First Server: tcp://127.0.0.1:24000")
    at GravityLogger.cpp:130
#6  0x00007f2563254800 in gravity::Log::vLog (level=8, format=0x441898 "[Lookup Request] ID: %s, Domain: %s, MessageType: Data Product, First Server: %s",
    args=0x7ffc149fc3c8) at GravityLogger.cpp:302
#7  0x00007f2563254c45 in gravity::Log::message (message=0x441898 "[Lookup Request] ID: %s, Domain: %s, MessageType: Data Product, First Server: %s")
    at GravityLogger.cpp:400
#8  0x000000000042bd7f in gravity::ServiceDirectory::handleLookup (this=0x7ffc149fca10, request=..., response=...) at ServiceDirectory.cpp:547
#9  0x000000000042b23e in gravity::ServiceDirectory::request (this=0x7ffc149fca10, dataProduct=...) at ServiceDirectory.cpp:433
#10 0x000000000042a4fd in gravity::ServiceDirectory::start (this=0x7ffc149fca10) at ServiceDirectory.cpp:358
#11 0x000000000042906b in main () at ServiceDirectory.cpp:68
```

**Comment by mbarger99** [comment]
Thanks for tracking this down.  I've seen a similar issue in the past when I've tried to write to a console logger, but the process had no console.  In that case though it was fairly clear what was going on since the only difference was in how the process was launched.  And it seemed reasonable that a process with no console should be configured with no console logging.

I've never run into a case like yours though.  Do you have any idea why you can't write to that file?  Is it locked by another process?  Or is the disk full?

Ultimately this seems to be a system level and/or configuration issue, but it would be good if Gravity could work around this problem when it occurs, or at least make it clear that something is blocked.  We'll look at some options here, including your threading suggestion.
